name: Build Branch II
# Runs build and uploads to Dummy Channel on App Center for the provided Build Flavor and Variant
# Build is ran based on branch, flavor, and variant provided.
on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Build Type
        options:
          - Debug
          - Release
      flavor:
        type: choice
        description: Build Flavor
        options:
          - Tst
          - TstZh
          - Uat2
          - Uat2Zh
          - Prod
          - ProdZh
      appdomeinput:
        type: boolean
        description: AppDome Build
        default: false

env:
  changeLog: changes.txt
  #ANDROID_HOME: /Users/rzmud035/Library/Android/sdk

jobs:
  build:
    runs-on: [ self-hosted, AWS-Mac-Android ]
    steps:   
      - shell: bash
        run: |
          echo "Setting Env"
          pwd
          rm -rf ../../_tool/Java_Temurin-Hotspot_jdk
          ls -lah ../../_tool/
          rm -rf ~/.gradle/caches
          ls -lah ~/.gradle          
          cp -r ~/.gradle/caches-old ~/.gradle/caches
          echo "branchName=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV        
          echo "NODE_EXTRA_CA_CERTS=.github/scripts/marriott_cacerts.pem" >> $GITHUB_ENV   
          echo "Env Set"
      - uses: actions/checkout@v3
        with:
          ref: ${{env.branchName}}          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16    
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 18.0.2+9
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        #if: ${{ false }}
        run: |
             pwd
             ls -lah 
             find . -name split-cert.sh
             cd ./.github/scripts
             ./split-cert.sh
             ls -lah
             cd -
             chmod +x gradlew          

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2          

      - name: Create Change Log
        if: ${{ false }}
        run: |
          "${{github.workspace}}/.github/scripts/generate_recent_changes.sh" -c "" -C "Adhoc Build ran by ${{ github.actor }}" -C "${appDomeChangeLog}" -o "${changeLog}"
          
      #- name: Setup Android SDK
      #  uses: android-actions/setup-android@v2
  
      - name: Build Dummy with Gradle
        #if: ${{ false }}
        run: |
             echo $JAVA_HOME
             ./gradlew clean
             find . -name "*.apk"
             ./gradlew build
             find . -name "*.apk" > results-apk.txt
      - name: Upload Results
        #if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: results-apk
          path: results-apk.txt  
